# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1064)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 150, 361, 891))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.toolBox = QtWidgets.QToolBox(self.frame)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 341, 841))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.toolBox.setFont(font)
        self.toolBox.setObjectName("toolBox")
        self.admin_spgl = QtWidgets.QWidget()
        self.admin_spgl.setGeometry(QtCore.QRect(0, 0, 341, 581))
        self.admin_spgl.setObjectName("admin_spgl")
        self.layoutWidget = QtWidgets.QWidget(self.admin_spgl)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 0, 301, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Admin_SPGL_LR = QtWidgets.QPushButton(self.layoutWidget)
        self.Admin_SPGL_LR.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_SPGL_LR.setFont(font)
        self.Admin_SPGL_LR.setObjectName("Admin_SPGL_LR")
        self.verticalLayout.addWidget(self.Admin_SPGL_LR)
        self.Admin_SPGL_LL = QtWidgets.QPushButton(self.layoutWidget)
        self.Admin_SPGL_LL.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_SPGL_LL.setFont(font)
        self.Admin_SPGL_LL.setObjectName("Admin_SPGL_LL")
        self.verticalLayout.addWidget(self.Admin_SPGL_LL)
        self.toolBox.addItem(self.admin_spgl, "")
        self.admin_hygl = QtWidgets.QWidget()
        self.admin_hygl.setGeometry(QtCore.QRect(0, 0, 341, 581))
        self.admin_hygl.setObjectName("admin_hygl")
        self.layoutWidget1 = QtWidgets.QWidget(self.admin_hygl)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 0, 301, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Admin_HYGL_LR = QtWidgets.QPushButton(self.layoutWidget1)
        self.Admin_HYGL_LR.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_HYGL_LR.setFont(font)
        self.Admin_HYGL_LR.setObjectName("Admin_HYGL_LR")
        self.verticalLayout_2.addWidget(self.Admin_HYGL_LR)
        self.Admin_HYGL_LL = QtWidgets.QPushButton(self.layoutWidget1)
        self.Admin_HYGL_LL.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_HYGL_LL.setFont(font)
        self.Admin_HYGL_LL.setObjectName("Admin_HYGL_LL")
        self.verticalLayout_2.addWidget(self.Admin_HYGL_LL)
        self.toolBox.addItem(self.admin_hygl, "")
        self.admin_yhgl = QtWidgets.QWidget()
        self.admin_yhgl.setGeometry(QtCore.QRect(0, 0, 341, 581))
        self.admin_yhgl.setObjectName("admin_yhgl")
        self.layoutWidget_2 = QtWidgets.QWidget(self.admin_yhgl)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 0, 301, 281))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Admin_YHGL_XTYH = QtWidgets.QPushButton(self.layoutWidget_2)
        self.Admin_YHGL_XTYH.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_YHGL_XTYH.setFont(font)
        self.Admin_YHGL_XTYH.setObjectName("Admin_YHGL_XTYH")
        self.verticalLayout_3.addWidget(self.Admin_YHGL_XTYH)
        self.Admin_YHGL_YGGL = QtWidgets.QPushButton(self.layoutWidget_2)
        self.Admin_YHGL_YGGL.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_YHGL_YGGL.setFont(font)
        self.Admin_YHGL_YGGL.setObjectName("Admin_YHGL_YGGL")
        self.verticalLayout_3.addWidget(self.Admin_YHGL_YGGL)
        self.Admin_YHGL_YGYJ = QtWidgets.QPushButton(self.layoutWidget_2)
        self.Admin_YHGL_YGYJ.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_YHGL_YGYJ.setFont(font)
        self.Admin_YHGL_YGYJ.setObjectName("Admin_YHGL_YGYJ")
        self.verticalLayout_3.addWidget(self.Admin_YHGL_YGYJ)
        self.toolBox.addItem(self.admin_yhgl, "")
        self.admin_tjcx = QtWidgets.QWidget()
        self.admin_tjcx.setGeometry(QtCore.QRect(0, 0, 341, 581))
        self.admin_tjcx.setObjectName("admin_tjcx")
        self.layoutWidget_3 = QtWidgets.QWidget(self.admin_tjcx)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 0, 301, 311))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Admin_TJFX_XSTJ = QtWidgets.QPushButton(self.layoutWidget_3)
        self.Admin_TJFX_XSTJ.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_TJFX_XSTJ.setFont(font)
        self.Admin_TJFX_XSTJ.setObjectName("Admin_TJFX_XSTJ")
        self.verticalLayout_4.addWidget(self.Admin_TJFX_XSTJ)
        self.Admin_TJFX_KCTJ = QtWidgets.QPushButton(self.layoutWidget_3)
        self.Admin_TJFX_KCTJ.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_TJFX_KCTJ.setFont(font)
        self.Admin_TJFX_KCTJ.setObjectName("Admin_TJFX_KCTJ")
        self.verticalLayout_4.addWidget(self.Admin_TJFX_KCTJ)
        self.Admin_TJFX_JYFX = QtWidgets.QPushButton(self.layoutWidget_3)
        self.Admin_TJFX_JYFX.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_TJFX_JYFX.setFont(font)
        self.Admin_TJFX_JYFX.setObjectName("Admin_TJFX_JYFX")
        self.verticalLayout_4.addWidget(self.Admin_TJFX_JYFX)
        self.Admin_TJFX_ZCTJ = QtWidgets.QPushButton(self.layoutWidget_3)
        self.Admin_TJFX_ZCTJ.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_TJFX_ZCTJ.setFont(font)
        self.Admin_TJFX_ZCTJ.setObjectName("Admin_TJFX_ZCTJ")
        self.verticalLayout_4.addWidget(self.Admin_TJFX_ZCTJ)
        self.toolBox.addItem(self.admin_tjcx, "")
        self.admin_xtsz = QtWidgets.QWidget()
        self.admin_xtsz.setGeometry(QtCore.QRect(0, 0, 341, 581))
        self.admin_xtsz.setObjectName("admin_xtsz")
        self.layoutWidget_4 = QtWidgets.QWidget(self.admin_xtsz)
        self.layoutWidget_4.setGeometry(QtCore.QRect(40, 0, 301, 141))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Admin_XTSZ_XTSZ = QtWidgets.QPushButton(self.layoutWidget_4)
        self.Admin_XTSZ_XTSZ.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_XTSZ_XTSZ.setFont(font)
        self.Admin_XTSZ_XTSZ.setObjectName("Admin_XTSZ_XTSZ")
        self.verticalLayout_5.addWidget(self.Admin_XTSZ_XTSZ)
        self.Admin_XTGL_GYRJ = QtWidgets.QPushButton(self.layoutWidget_4)
        self.Admin_XTGL_GYRJ.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Admin_XTGL_GYRJ.setFont(font)
        self.Admin_XTGL_GYRJ.setObjectName("Admin_XTGL_GYRJ")
        self.verticalLayout_5.addWidget(self.Admin_XTGL_GYRJ)
        self.toolBox.addItem(self.admin_xtsz, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 901, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Display_layer = QtWidgets.QStackedWidget(self.centralwidget)
        self.Display_layer.setGeometry(QtCore.QRect(370, 150, 1501, 891))
        self.Display_layer.setObjectName("Display_layer")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(460, 250, 901, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Display_layer.addWidget(self.page)
        self.layer1 = QtWidgets.QWidget()
        self.layer1.setObjectName("layer1")
        self.Spgl_tj_button = QtWidgets.QPushButton(self.layer1)
        self.Spgl_tj_button.setGeometry(QtCore.QRect(1160, 790, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Spgl_tj_button.setFont(font)
        self.Spgl_tj_button.setObjectName("Spgl_tj_button")
        self.layoutWidget_5 = QtWidgets.QWidget(self.layer1)
        self.layoutWidget_5.setGeometry(QtCore.QRect(70, 30, 671, 541))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_6.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_6.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_6.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_6.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_6.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_6.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_6.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_6.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_6.addWidget(self.label_27)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Spgl_sptm = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Spgl_sptm.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Spgl_sptm.setFont(font)
        self.Spgl_sptm.setObjectName("Spgl_sptm")
        self.verticalLayout_7.addWidget(self.Spgl_sptm)
        self.Spgl_spmc = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Spgl_spmc.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Spgl_spmc.setFont(font)
        self.Spgl_spmc.setText("")
        self.Spgl_spmc.setObjectName("Spgl_spmc")
        self.verticalLayout_7.addWidget(self.Spgl_spmc)
        self.Spgl_spgg = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Spgl_spgg.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Spgl_spgg.setFont(font)
        self.Spgl_spgg.setText("")
        self.Spgl_spgg.setObjectName("Spgl_spgg")
        self.verticalLayout_7.addWidget(self.Spgl_spgg)
        self.Spgl_splb = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Spgl_splb.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Spgl_splb.setFont(font)
        self.Spgl_splb.setText("")
        self.Spgl_splb.setObjectName("Spgl_splb")
        self.verticalLayout_7.addWidget(self.Spgl_splb)
        self.Spgl_spsl = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Spgl_spsl.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Spgl_spsl.setFont(font)
        self.Spgl_spsl.setText("")
        self.Spgl_spsl.setObjectName("Spgl_spsl")
        self.verticalLayout_7.addWidget(self.Spgl_spsl)
        self.Spgl_spdw = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Spgl_spdw.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Spgl_spdw.setFont(font)
        self.Spgl_spdw.setObjectName("Spgl_spdw")
        self.verticalLayout_7.addWidget(self.Spgl_spdw)
        self.Spgl_spjj = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Spgl_spjj.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Spgl_spjj.setFont(font)
        self.Spgl_spjj.setText("")
        self.Spgl_spjj.setObjectName("Spgl_spjj")
        self.verticalLayout_7.addWidget(self.Spgl_spjj)
        self.Spgl_sphyj = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Spgl_sphyj.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Spgl_sphyj.setFont(font)
        self.Spgl_sphyj.setText("")
        self.Spgl_sphyj.setObjectName("Spgl_sphyj")
        self.verticalLayout_7.addWidget(self.Spgl_sphyj)
        self.Spgl_splsj = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Spgl_splsj.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Spgl_splsj.setFont(font)
        self.Spgl_splsj.setText("")
        self.Spgl_splsj.setObjectName("Spgl_splsj")
        self.verticalLayout_7.addWidget(self.Spgl_splsj)
        self.Spgl_spghs = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Spgl_spghs.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Spgl_spghs.setFont(font)
        self.Spgl_spghs.setText("")
        self.Spgl_spghs.setObjectName("Spgl_spghs")
        self.verticalLayout_7.addWidget(self.Spgl_spghs)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.line = QtWidgets.QFrame(self.layer1)
        self.line.setGeometry(QtCore.QRect(40, 760, 1451, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget_6 = QtWidgets.QWidget(self.layer1)
        self.layoutWidget_6.setGeometry(QtCore.QRect(830, 100, 625, 103))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.Spgl_splr_zh_name = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.Spgl_splr_zh_name.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Spgl_splr_zh_name.setFont(font)
        self.Spgl_splr_zh_name.setObjectName("Spgl_splr_zh_name")
        self.horizontalLayout_4.addWidget(self.Spgl_splr_zh_name)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.Spgl_splr_zh_cash = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.Spgl_splr_zh_cash.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Spgl_splr_zh_cash.setFont(font)
        self.Spgl_splr_zh_cash.setObjectName("Spgl_splr_zh_cash")
        self.horizontalLayout_4.addWidget(self.Spgl_splr_zh_cash)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_5.addWidget(self.label_29)
        self.Spgl_splr_tm_width = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.Spgl_splr_tm_width.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Spgl_splr_tm_width.setFont(font)
        self.Spgl_splr_tm_width.setObjectName("Spgl_splr_tm_width")
        self.horizontalLayout_5.addWidget(self.Spgl_splr_tm_width)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_5.addWidget(self.label_30)
        self.Spgl_splr_tm_height = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.Spgl_splr_tm_height.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Spgl_splr_tm_height.setFont(font)
        self.Spgl_splr_tm_height.setObjectName("Spgl_splr_tm_height")
        self.horizontalLayout_5.addWidget(self.Spgl_splr_tm_height)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_5.addWidget(self.label_31)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_6.addWidget(self.label_32)
        self.Spgl_splr_pagelift_margin = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.Spgl_splr_pagelift_margin.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Spgl_splr_pagelift_margin.setFont(font)
        self.Spgl_splr_pagelift_margin.setObjectName("Spgl_splr_pagelift_margin")
        self.horizontalLayout_6.addWidget(self.Spgl_splr_pagelift_margin)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_6.addWidget(self.label_33)
        self.Spgl_splr_pageright_margin = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.Spgl_splr_pageright_margin.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Spgl_splr_pageright_margin.setFont(font)
        self.Spgl_splr_pageright_margin.setObjectName("Spgl_splr_pageright_margin")
        self.horizontalLayout_6.addWidget(self.Spgl_splr_pageright_margin)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_6.addWidget(self.label_34)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.Spgl_splr_ylxg = QtWidgets.QTextEdit(self.layer1)
        self.Spgl_splr_ylxg.setGeometry(QtCore.QRect(830, 230, 631, 331))
        self.Spgl_splr_ylxg.setObjectName("Spgl_splr_ylxg")
        self.Spgl_splr_print = QtWidgets.QPushButton(self.layer1)
        self.Spgl_splr_print.setGeometry(QtCore.QRect(1300, 600, 151, 35))
        self.Spgl_splr_print.setMinimumSize(QtCore.QSize(0, 35))
        self.Spgl_splr_print.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Spgl_splr_print.setFont(font)
        self.Spgl_splr_print.setObjectName("Spgl_splr_print")
        self.layoutWidget2 = QtWidgets.QWidget(self.layer1)
        self.layoutWidget2.setGeometry(QtCore.QRect(770, 40, 321, 37))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Spgl_splr_random = QtWidgets.QPushButton(self.layoutWidget2)
        self.Spgl_splr_random.setMinimumSize(QtCore.QSize(0, 35))
        self.Spgl_splr_random.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Spgl_splr_random.setFont(font)
        self.Spgl_splr_random.setObjectName("Spgl_splr_random")
        self.horizontalLayout_7.addWidget(self.Spgl_splr_random)
        self.Spgl_splr_bqsc = QtWidgets.QPushButton(self.layoutWidget2)
        self.Spgl_splr_bqsc.setMinimumSize(QtCore.QSize(0, 35))
        self.Spgl_splr_bqsc.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Spgl_splr_bqsc.setFont(font)
        self.Spgl_splr_bqsc.setObjectName("Spgl_splr_bqsc")
        self.horizontalLayout_7.addWidget(self.Spgl_splr_bqsc)
        self.Display_layer.addWidget(self.layer1)
        self.layer2 = QtWidgets.QWidget()
        self.layer2.setObjectName("layer2")
        self.SPGL_sqll_table = QtWidgets.QTableWidget(self.layer2)
        self.SPGL_sqll_table.setGeometry(QtCore.QRect(0, 0, 1491, 851))
        self.SPGL_sqll_table.setObjectName("SPGL_sqll_table")
        self.SPGL_sqll_table.setColumnCount(11)
        self.SPGL_sqll_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.SPGL_sqll_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SPGL_sqll_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SPGL_sqll_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SPGL_sqll_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SPGL_sqll_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SPGL_sqll_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.SPGL_sqll_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.SPGL_sqll_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.SPGL_sqll_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.SPGL_sqll_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.SPGL_sqll_table.setHorizontalHeaderItem(10, item)
        self.SPGL_sqll_table.horizontalHeader().setCascadingSectionResizes(True)
        self.SPGL_sqll_table.horizontalHeader().setDefaultSectionSize(130)
        self.SPGL_sqll_table.horizontalHeader().setMinimumSectionSize(20)
        self.SPGL_sqll_table.horizontalHeader().setSortIndicatorShown(True)
        self.SPGL_sqll_table.horizontalHeader().setStretchLastSection(False)
        self.SPGL_sqll_table.verticalHeader().setVisible(False)
        self.SPGL_sqll_table.verticalHeader().setCascadingSectionResizes(False)
        self.SPGL_sqll_table.verticalHeader().setDefaultSectionSize(20)
        self.SPGL_sqll_table.verticalHeader().setMinimumSectionSize(20)
        self.SPGL_sqll_table.verticalHeader().setSortIndicatorShown(False)
        self.SPGL_sqll_table.verticalHeader().setStretchLastSection(False)
        self.Display_layer.addWidget(self.layer2)
        self.layer4 = QtWidgets.QWidget()
        self.layer4.setObjectName("layer4")
        self.label_7 = QtWidgets.QLabel(self.layer4)
        self.label_7.setGeometry(QtCore.QRect(410, 140, 771, 221))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Display_layer.addWidget(self.layer4)
        self.layer5 = QtWidgets.QWidget()
        self.layer5.setObjectName("layer5")
        self.label_8 = QtWidgets.QLabel(self.layer5)
        self.label_8.setGeometry(QtCore.QRect(470, 230, 701, 401))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.Display_layer.addWidget(self.layer5)
        self.layer6 = QtWidgets.QWidget()
        self.layer6.setObjectName("layer6")
        self.label_9 = QtWidgets.QLabel(self.layer6)
        self.label_9.setGeometry(QtCore.QRect(480, 100, 721, 501))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Display_layer.addWidget(self.layer6)
        self.layer7 = QtWidgets.QWidget()
        self.layer7.setObjectName("layer7")
        self.label_10 = QtWidgets.QLabel(self.layer7)
        self.label_10.setGeometry(QtCore.QRect(430, 190, 811, 421))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.Display_layer.addWidget(self.layer7)
        self.layer8 = QtWidgets.QWidget()
        self.layer8.setObjectName("layer8")
        self.label_11 = QtWidgets.QLabel(self.layer8)
        self.label_11.setGeometry(QtCore.QRect(340, 340, 811, 221))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.Display_layer.addWidget(self.layer8)
        self.layer9 = QtWidgets.QWidget()
        self.layer9.setObjectName("layer9")
        self.Display_layer.addWidget(self.layer9)
        self.layer10 = QtWidgets.QWidget()
        self.layer10.setObjectName("layer10")
        self.label_3 = QtWidgets.QLabel(self.layer10)
        self.label_3.setGeometry(QtCore.QRect(310, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.layer10)
        self.label_5.setGeometry(QtCore.QRect(1070, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.splitter = QtWidgets.QSplitter(self.layer10)
        self.splitter.setGeometry(QtCore.QRect(10, 120, 1470, 700))
        self.splitter.setMinimumSize(QtCore.QSize(500, 700))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.TJFX_xstj_xstj = QtWidgets.QTableWidget(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TJFX_xstj_xstj.setFont(font)
        self.TJFX_xstj_xstj.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TJFX_xstj_xstj.setObjectName("TJFX_xstj_xstj")
        self.TJFX_xstj_xstj.setColumnCount(3)
        self.TJFX_xstj_xstj.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TJFX_xstj_xstj.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TJFX_xstj_xstj.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TJFX_xstj_xstj.setHorizontalHeaderItem(2, item)
        self.TJFX_xstj_xstj.horizontalHeader().setDefaultSectionSize(240)
        self.TJFX_xstj_xsmx = QtWidgets.QTableWidget(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TJFX_xstj_xsmx.setFont(font)
        self.TJFX_xstj_xsmx.setAutoScrollMargin(16)
        self.TJFX_xstj_xsmx.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TJFX_xstj_xsmx.setObjectName("TJFX_xstj_xsmx")
        self.TJFX_xstj_xsmx.setColumnCount(5)
        self.TJFX_xstj_xsmx.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TJFX_xstj_xsmx.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TJFX_xstj_xsmx.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TJFX_xstj_xsmx.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TJFX_xstj_xsmx.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TJFX_xstj_xsmx.setHorizontalHeaderItem(4, item)
        self.TJFX_xstj_xsmx.horizontalHeader().setDefaultSectionSize(145)
        self.layoutWidget3 = QtWidgets.QWidget(self.layer10)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 10, 904, 38))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_4.setMinimumSize(QtCore.QSize(30, 30))
        self.label_4.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.TJFX_xstj_starttime = QtWidgets.QDateEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TJFX_xstj_starttime.setFont(font)
        self.TJFX_xstj_starttime.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 9, 1), QtCore.QTime(0, 0, 0)))
        self.TJFX_xstj_starttime.setCalendarPopup(True)
        self.TJFX_xstj_starttime.setObjectName("TJFX_xstj_starttime")
        self.horizontalLayout.addWidget(self.TJFX_xstj_starttime)
        self.TJFX_xstj_finishtime = QtWidgets.QDateEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TJFX_xstj_finishtime.setFont(font)
        self.TJFX_xstj_finishtime.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 9, 1), QtCore.QTime(0, 0, 0)))
        self.TJFX_xstj_finishtime.setCalendarPopup(True)
        self.TJFX_xstj_finishtime.setObjectName("TJFX_xstj_finishtime")
        self.horizontalLayout.addWidget(self.TJFX_xstj_finishtime)
        self.TJFX_xstj_user = QtWidgets.QComboBox(self.layoutWidget3)
        self.TJFX_xstj_user.setMinimumSize(QtCore.QSize(200, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TJFX_xstj_user.setFont(font)
        self.TJFX_xstj_user.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TJFX_xstj_user.setObjectName("TJFX_xstj_user")
        self.horizontalLayout.addWidget(self.TJFX_xstj_user)
        self.TJFX_xstj_CX_button = QtWidgets.QPushButton(self.layoutWidget3)
        self.TJFX_xstj_CX_button.setMinimumSize(QtCore.QSize(150, 30))
        self.TJFX_xstj_CX_button.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.TJFX_xstj_CX_button.setFont(font)
        self.TJFX_xstj_CX_button.setObjectName("TJFX_xstj_CX_button")
        self.horizontalLayout.addWidget(self.TJFX_xstj_CX_button)
        self.layoutWidget4 = QtWidgets.QWidget(self.layer10)
        self.layoutWidget4.setGeometry(QtCore.QRect(500, 830, 571, 41))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_13.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.TJFX_xstj_xs_sum = QtWidgets.QLabel(self.layoutWidget4)
        self.TJFX_xstj_xs_sum.setMinimumSize(QtCore.QSize(100, 0))
        self.TJFX_xstj_xs_sum.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TJFX_xstj_xs_sum.setFont(font)
        self.TJFX_xstj_xs_sum.setObjectName("TJFX_xstj_xs_sum")
        self.horizontalLayout_3.addWidget(self.TJFX_xstj_xs_sum)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_28.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_3.addWidget(self.label_28)
        self.TJFX_xstj_lr_sum = QtWidgets.QLabel(self.layoutWidget4)
        self.TJFX_xstj_lr_sum.setMinimumSize(QtCore.QSize(100, 0))
        self.TJFX_xstj_lr_sum.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TJFX_xstj_lr_sum.setFont(font)
        self.TJFX_xstj_lr_sum.setObjectName("TJFX_xstj_lr_sum")
        self.horizontalLayout_3.addWidget(self.TJFX_xstj_lr_sum)
        self.Display_layer.addWidget(self.layer10)
        self.layer11 = QtWidgets.QWidget()
        self.layer11.setObjectName("layer11")
        self.label_14 = QtWidgets.QLabel(self.layer11)
        self.label_14.setGeometry(QtCore.QRect(430, 270, 851, 221))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.Display_layer.addWidget(self.layer11)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.EXPEND_xstj_starttime = QtWidgets.QDateEdit(self.page_2)
        self.EXPEND_xstj_starttime.setGeometry(QtCore.QRect(23, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EXPEND_xstj_starttime.setFont(font)
        self.EXPEND_xstj_starttime.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 9, 1), QtCore.QTime(0, 0, 0)))
        self.EXPEND_xstj_starttime.setCalendarPopup(True)
        self.EXPEND_xstj_starttime.setObjectName("EXPEND_xstj_starttime")
        self.EXPEND_xstj_CX_button = QtWidgets.QPushButton(self.page_2)
        self.EXPEND_xstj_CX_button.setGeometry(QtCore.QRect(710, 30, 150, 30))
        self.EXPEND_xstj_CX_button.setMinimumSize(QtCore.QSize(150, 30))
        self.EXPEND_xstj_CX_button.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.EXPEND_xstj_CX_button.setFont(font)
        self.EXPEND_xstj_CX_button.setObjectName("EXPEND_xstj_CX_button")
        self.EXPEND_xstj_finishtime = QtWidgets.QDateEdit(self.page_2)
        self.EXPEND_xstj_finishtime.setGeometry(QtCore.QRect(251, 30, 222, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EXPEND_xstj_finishtime.setFont(font)
        self.EXPEND_xstj_finishtime.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 9, 1), QtCore.QTime(0, 0, 0)))
        self.EXPEND_xstj_finishtime.setCalendarPopup(True)
        self.EXPEND_xstj_finishtime.setObjectName("EXPEND_xstj_finishtime")
        self.Expend_table = QtWidgets.QTableWidget(self.page_2)
        self.Expend_table.setGeometry(QtCore.QRect(20, 90, 1451, 721))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Expend_table.setFont(font)
        self.Expend_table.setDragEnabled(False)
        self.Expend_table.setAlternatingRowColors(False)
        self.Expend_table.setObjectName("Expend_table")
        self.Expend_table.setColumnCount(4)
        self.Expend_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Expend_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Expend_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Expend_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Expend_table.setHorizontalHeaderItem(3, item)
        self.Expend_table.horizontalHeader().setCascadingSectionResizes(False)
        self.Expend_table.horizontalHeader().setSortIndicatorShown(False)
        self.Expend_table.horizontalHeader().setStretchLastSection(False)
        self.Expend_table.verticalHeader().setCascadingSectionResizes(False)
        self.Expend_table.verticalHeader().setSortIndicatorShown(False)
        self.Expend_table.verticalHeader().setStretchLastSection(False)
        self.layoutWidget_7 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_7.setGeometry(QtCore.QRect(900, 830, 571, 41))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_36.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_8.addWidget(self.label_36)
        self.EXPEND_xstj_lr_sum = QtWidgets.QLabel(self.layoutWidget_7)
        self.EXPEND_xstj_lr_sum.setMinimumSize(QtCore.QSize(100, 0))
        self.EXPEND_xstj_lr_sum.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EXPEND_xstj_lr_sum.setFont(font)
        self.EXPEND_xstj_lr_sum.setObjectName("EXPEND_xstj_lr_sum")
        self.horizontalLayout_8.addWidget(self.EXPEND_xstj_lr_sum)
        self.ZCFX_xstj_name = QtWidgets.QComboBox(self.page_2)
        self.ZCFX_xstj_name.setGeometry(QtCore.QRect(480, 30, 221, 31))
        self.ZCFX_xstj_name.setMinimumSize(QtCore.QSize(200, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ZCFX_xstj_name.setFont(font)
        self.ZCFX_xstj_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ZCFX_xstj_name.setObjectName("ZCFX_xstj_name")
        self.ZCFX_xstj_name.addItem("")
        self.ZCFX_xstj_name.addItem("")
        self.ZCFX_xstj_name.addItem("")
        self.ZCFX_xstj_name.addItem("")
        self.ZCFX_xstj_name.addItem("")
        self.Display_layer.addWidget(self.page_2)
        self.layer12 = QtWidgets.QWidget()
        self.layer12.setObjectName("layer12")
        self.label_15 = QtWidgets.QLabel(self.layer12)
        self.label_15.setGeometry(QtCore.QRect(630, 340, 501, 311))
        font = QtGui.QFont()
        font.setPointSize(33)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.Display_layer.addWidget(self.layer12)
        self.layer14 = QtWidgets.QWidget()
        self.layer14.setObjectName("layer14")
        self.label_17 = QtWidgets.QLabel(self.layer14)
        self.label_17.setGeometry(QtCore.QRect(250, 270, 1061, 221))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.Display_layer.addWidget(self.layer14)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.Display_layer.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Admin_SPGL_LR.setText(_translate("MainWindow", "商品录入"))
        self.Admin_SPGL_LL.setText(_translate("MainWindow", "商品浏览"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.admin_spgl), _translate("MainWindow", "商品管理"))
        self.Admin_HYGL_LR.setText(_translate("MainWindow", "会员录入"))
        self.Admin_HYGL_LL.setText(_translate("MainWindow", "会员浏览"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.admin_hygl), _translate("MainWindow", "会员管理"))
        self.Admin_YHGL_XTYH.setText(_translate("MainWindow", "系统用户"))
        self.Admin_YHGL_YGGL.setText(_translate("MainWindow", "员工管理"))
        self.Admin_YHGL_YGYJ.setText(_translate("MainWindow", "员工业绩"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.admin_yhgl), _translate("MainWindow", "用户管理"))
        self.Admin_TJFX_XSTJ.setText(_translate("MainWindow", "销售统计"))
        self.Admin_TJFX_KCTJ.setText(_translate("MainWindow", "库存统计"))
        self.Admin_TJFX_JYFX.setText(_translate("MainWindow", "经营分析"))
        self.Admin_TJFX_ZCTJ.setText(_translate("MainWindow", "支出统计"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.admin_tjcx), _translate("MainWindow", "统计分析"))
        self.Admin_XTSZ_XTSZ.setText(_translate("MainWindow", "系统设置"))
        self.Admin_XTGL_GYRJ.setText(_translate("MainWindow", "关于软件"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.admin_xtsz), _translate("MainWindow", "系统设置"))
        self.label.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "2"))
        self.Spgl_tj_button.setText(_translate("MainWindow", "商品入库"))
        self.label_18.setText(_translate("MainWindow", "商品条码(*):"))
        self.label_19.setText(_translate("MainWindow", "商品名称(*):"))
        self.label_20.setText(_translate("MainWindow", "商品规格:"))
        self.label_21.setText(_translate("MainWindow", "商品类别："))
        self.label_22.setText(_translate("MainWindow", "商品数量:"))
        self.label_23.setText(_translate("MainWindow", "商品单位:"))
        self.label_24.setText(_translate("MainWindow", "商品进价:"))
        self.label_25.setText(_translate("MainWindow", "商品会员价："))
        self.label_26.setText(_translate("MainWindow", "商品零售价:"))
        self.label_27.setText(_translate("MainWindow", "供货商:"))
        self.Spgl_spdw.setText(_translate("MainWindow", "件"))
        self.label_6.setText(_translate("MainWindow", "设置大小："))
        self.Spgl_splr_zh_name.setText(_translate("MainWindow", "3"))
        self.label_12.setText(_translate("MainWindow", "名称"))
        self.Spgl_splr_zh_cash.setText(_translate("MainWindow", "3"))
        self.label_16.setText(_translate("MainWindow", "价格"))
        self.label_29.setText(_translate("MainWindow", "条码大小："))
        self.Spgl_splr_tm_width.setText(_translate("MainWindow", "150"))
        self.label_30.setText(_translate("MainWindow", "宽"))
        self.Spgl_splr_tm_height.setText(_translate("MainWindow", "55"))
        self.label_31.setText(_translate("MainWindow", "高"))
        self.label_32.setText(_translate("MainWindow", "设置边距："))
        self.Spgl_splr_pagelift_margin.setText(_translate("MainWindow", "19.5"))
        self.label_33.setText(_translate("MainWindow", "左"))
        self.Spgl_splr_pageright_margin.setText(_translate("MainWindow", "1.6"))
        self.label_34.setText(_translate("MainWindow", "左上"))
        self.Spgl_splr_print.setText(_translate("MainWindow", "打印标签"))
        self.Spgl_splr_random.setText(_translate("MainWindow", "生成随机条码"))
        self.Spgl_splr_bqsc.setText(_translate("MainWindow", "生成标签"))
        item = self.SPGL_sqll_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.SPGL_sqll_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "货号"))
        item = self.SPGL_sqll_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "名称"))
        item = self.SPGL_sqll_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "规格"))
        item = self.SPGL_sqll_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "类别"))
        item = self.SPGL_sqll_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "库存"))
        item = self.SPGL_sqll_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "售出"))
        item = self.SPGL_sqll_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "单位"))
        item = self.SPGL_sqll_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "零售价"))
        item = self.SPGL_sqll_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "进价"))
        item = self.SPGL_sqll_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "供应商"))
        self.label_7.setText(_translate("MainWindow", "会员录入"))
        self.label_8.setText(_translate("MainWindow", "会员浏览"))
        self.label_9.setText(_translate("MainWindow", "系统用户"))
        self.label_10.setText(_translate("MainWindow", "员工管理"))
        self.label_11.setText(_translate("MainWindow", "员工业绩"))
        self.label_3.setText(_translate("MainWindow", "销售统计"))
        self.label_5.setText(_translate("MainWindow", "销售明细"))
        item = self.TJFX_xstj_xstj.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "日期"))
        item = self.TJFX_xstj_xstj.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "销售额"))
        item = self.TJFX_xstj_xstj.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "毛利润"))
        item = self.TJFX_xstj_xsmx.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "货号"))
        item = self.TJFX_xstj_xsmx.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.TJFX_xstj_xsmx.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "规格"))
        item = self.TJFX_xstj_xsmx.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "数量"))
        item = self.TJFX_xstj_xsmx.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "金额"))
        self.label_4.setText(_translate("MainWindow", "时间："))
        self.TJFX_xstj_starttime.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.TJFX_xstj_finishtime.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.TJFX_xstj_CX_button.setText(_translate("MainWindow", "查询"))
        self.label_13.setText(_translate("MainWindow", "销售合计："))
        self.TJFX_xstj_xs_sum.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "利润合计："))
        self.TJFX_xstj_lr_sum.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "经营分析"))
        self.EXPEND_xstj_starttime.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.EXPEND_xstj_CX_button.setText(_translate("MainWindow", "查询"))
        self.EXPEND_xstj_finishtime.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        item = self.Expend_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "日期"))
        item = self.Expend_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "内容"))
        item = self.Expend_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "金额"))
        item = self.Expend_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "备注"))
        self.label_36.setText(_translate("MainWindow", "支出合计："))
        self.EXPEND_xstj_lr_sum.setText(_translate("MainWindow", "0"))
        self.ZCFX_xstj_name.setItemText(0, _translate("MainWindow", "全部类别"))
        self.ZCFX_xstj_name.setItemText(1, _translate("MainWindow", "服装采购"))
        self.ZCFX_xstj_name.setItemText(2, _translate("MainWindow", "店面装修"))
        self.ZCFX_xstj_name.setItemText(3, _translate("MainWindow", "日常物品采购"))
        self.ZCFX_xstj_name.setItemText(4, _translate("MainWindow", "其它"))
        self.label_15.setText(_translate("MainWindow", "系统设置"))
        self.label_17.setText(_translate("MainWindow", "关于软件"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
