# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inquireui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1166, 435)
        MainWindow.setMinimumSize(QtCore.QSize(1166, 435))
        MainWindow.setMaximumSize(QtCore.QSize(1166, 435))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.SPselect_Button = QtWidgets.QPushButton(self.centralwidget)
        self.SPselect_Button.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SPselect_Button.setFont(font)
        self.SPselect_Button.setObjectName("SPselect_Button")
        self.gridLayout.addWidget(self.SPselect_Button, 1, 1, 1, 1)
        self.SPselect_table = QtWidgets.QTableWidget(self.centralwidget)
        self.SPselect_table.setMinimumSize(QtCore.QSize(1100, 0))
        self.SPselect_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.SPselect_table.setObjectName("SPselect_table")
        self.SPselect_table.setColumnCount(7)
        self.SPselect_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.SPselect_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(218, 218, 218))
        self.SPselect_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.SPselect_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(218, 218, 218))
        self.SPselect_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(218, 218, 218))
        self.SPselect_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(218, 218, 218))
        self.SPselect_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(218, 218, 218))
        self.SPselect_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(218, 218, 218))
        self.SPselect_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SPselect_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SPselect_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SPselect_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SPselect_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SPselect_table.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SPselect_table.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SPselect_table.setItem(0, 6, item)
        self.SPselect_table.horizontalHeader().setDefaultSectionSize(160)
        self.gridLayout.addWidget(self.SPselect_table, 2, 0, 1, 2)
        self.SPselect_input = QtWidgets.QLineEdit(self.centralwidget)
        self.SPselect_input.setMinimumSize(QtCore.QSize(100, 30))
        self.SPselect_input.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SPselect_input.setFont(font)
        self.SPselect_input.setObjectName("SPselect_input")
        self.gridLayout.addWidget(self.SPselect_input, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "商品编码/名称："))
        self.SPselect_Button.setText(_translate("MainWindow", "查询"))
        item = self.SPselect_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "条码"))
        item = self.SPselect_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.SPselect_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "规格"))
        item = self.SPselect_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "类别"))
        item = self.SPselect_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "库存"))
        item = self.SPselect_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "已卖出"))
        item = self.SPselect_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "零售价"))
        __sortingEnabled = self.SPselect_table.isSortingEnabled()
        self.SPselect_table.setSortingEnabled(False)
        self.SPselect_table.setSortingEnabled(__sortingEnabled)
