# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'returnbackui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1550, 674)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1550, 674))
        mainWindow.setMaximumSize(QtCore.QSize(1550, 674))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.RE_LSCX_text = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RE_LSCX_text.sizePolicy().hasHeightForWidth())
        self.RE_LSCX_text.setSizePolicy(sizePolicy)
        self.RE_LSCX_text.setMinimumSize(QtCore.QSize(270, 30))
        self.RE_LSCX_text.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.RE_LSCX_text.setFont(font)
        self.RE_LSCX_text.setObjectName("RE_LSCX_text")
        self.horizontalLayout_2.addWidget(self.RE_LSCX_text)
        self.RE_LSCX_button = QtWidgets.QPushButton(self.centralwidget)
        self.RE_LSCX_button.setMinimumSize(QtCore.QSize(150, 30))
        self.RE_LSCX_button.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.RE_LSCX_button.setFont(font)
        self.RE_LSCX_button.setObjectName("RE_LSCX_button")
        self.horizontalLayout_2.addWidget(self.RE_LSCX_button)
        spacerItem = QtWidgets.QSpacerItem(1020, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.RE_GWQS_date = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.RE_GWQS_date.setFont(font)
        self.RE_GWQS_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 9, 1), QtCore.QTime(0, 0, 0)))
        self.RE_GWQS_date.setCalendarPopup(True)
        self.RE_GWQS_date.setDate(QtCore.QDate(2019, 9, 1))
        self.RE_GWQS_date.setObjectName("RE_GWQS_date")
        self.horizontalLayout.addWidget(self.RE_GWQS_date)
        self.RE_GWJS_date = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.RE_GWJS_date.setFont(font)
        self.RE_GWJS_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 9, 1), QtCore.QTime(0, 0, 0)))
        self.RE_GWJS_date.setCalendarPopup(True)
        self.RE_GWJS_date.setObjectName("RE_GWJS_date")
        self.horizontalLayout.addWidget(self.RE_GWJS_date)
        self.RE_GWXC_button = QtWidgets.QPushButton(self.centralwidget)
        self.RE_GWXC_button.setMinimumSize(QtCore.QSize(150, 30))
        self.RE_GWXC_button.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.RE_GWXC_button.setFont(font)
        self.RE_GWXC_button.setObjectName("RE_GWXC_button")
        self.horizontalLayout.addWidget(self.RE_GWXC_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.TH_table = QtWidgets.QTableWidget(self.centralwidget)
        self.TH_table.setMinimumSize(QtCore.QSize(1500, 520))
        self.TH_table.setMaximumSize(QtCore.QSize(1200, 520))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.TH_table.setFont(font)
        self.TH_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TH_table.setObjectName("TH_table")
        self.TH_table.setColumnCount(8)
        self.TH_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TH_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TH_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TH_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TH_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TH_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TH_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TH_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TH_table.setHorizontalHeaderItem(7, item)
        self.TH_table.horizontalHeader().setDefaultSectionSize(160)
        self.gridLayout_2.addWidget(self.TH_table, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.TH_je_line = QtWidgets.QLineEdit(self.centralwidget)
        self.TH_je_line.setMinimumSize(QtCore.QSize(100, 0))
        self.TH_je_line.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.TH_je_line.setFont(font)
        self.TH_je_line.setReadOnly(True)
        self.TH_je_line.setObjectName("TH_je_line")
        self.gridLayout.addWidget(self.TH_je_line, 0, 9, 1, 1)
        self.TH_d_line = QtWidgets.QLineEdit(self.centralwidget)
        self.TH_d_line.setMinimumSize(QtCore.QSize(120, 0))
        self.TH_d_line.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.TH_d_line.setFont(font)
        self.TH_d_line.setReadOnly(True)
        self.TH_d_line.setObjectName("TH_d_line")
        self.gridLayout.addWidget(self.TH_d_line, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.TH_people_line = QtWidgets.QLineEdit(self.centralwidget)
        self.TH_people_line.setMinimumSize(QtCore.QSize(120, 0))
        self.TH_people_line.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.TH_people_line.setFont(font)
        self.TH_people_line.setReadOnly(True)
        self.TH_people_line.setObjectName("TH_people_line")
        self.gridLayout.addWidget(self.TH_people_line, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 6, 1, 1)
        self.TH_sl_line = QtWidgets.QLineEdit(self.centralwidget)
        self.TH_sl_line.setMinimumSize(QtCore.QSize(100, 0))
        self.TH_sl_line.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.TH_sl_line.setFont(font)
        self.TH_sl_line.setReadOnly(True)
        self.TH_sl_line.setObjectName("TH_sl_line")
        self.gridLayout.addWidget(self.TH_sl_line, 0, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(260, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 8, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 10, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.RE_TJ_button = QtWidgets.QPushButton(self.centralwidget)
        self.RE_TJ_button.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.RE_TJ_button.setFont(font)
        self.RE_TJ_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.RE_TJ_button.setObjectName("RE_TJ_button")
        self.gridLayout.addWidget(self.RE_TJ_button, 0, 11, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(260, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "退货"))
        self.label_6.setText(_translate("mainWindow", "流水号："))
        self.RE_LSCX_button.setText(_translate("mainWindow", "查询"))
        self.label_4.setText(_translate("mainWindow", "购物时间："))
        self.RE_GWQS_date.setDisplayFormat(_translate("mainWindow", "yyyy-MM-dd"))
        self.RE_GWJS_date.setDisplayFormat(_translate("mainWindow", "yyyy-MM-dd"))
        self.RE_GWXC_button.setText(_translate("mainWindow", "查询"))
        item = self.TH_table.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "序号"))
        item = self.TH_table.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "条码"))
        item = self.TH_table.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "名称"))
        item = self.TH_table.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "规格"))
        item = self.TH_table.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "数量"))
        item = self.TH_table.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "单价"))
        item = self.TH_table.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "折扣"))
        item = self.TH_table.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "金额"))
        self.label_7.setText(_translate("mainWindow", "退货门店"))
        self.label_2.setText(_translate("mainWindow", "销售员"))
        self.label_3.setText(_translate("mainWindow", "数量"))
        self.label_5.setText(_translate("mainWindow", "金额"))
        self.label.setText(_translate("mainWindow", "统计："))
        self.RE_TJ_button.setText(_translate("mainWindow", "提交"))
