# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statisticsui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1428, 674)
        MainWindow.setMinimumSize(QtCore.QSize(1428, 674))
        MainWindow.setMaximumSize(QtCore.QSize(1428, 674))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.QS_date = QtWidgets.QDateEdit(self.centralwidget)
        self.QS_date.setMinimumSize(QtCore.QSize(0, 30))
        self.QS_date.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.QS_date.setFont(font)
        self.QS_date.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.QS_date.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.QS_date.setAccelerated(False)
        self.QS_date.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.QS_date.setProperty("showGroupSeparator", False)
        self.QS_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 10, 1), QtCore.QTime(0, 0, 0)))
        self.QS_date.setCalendarPopup(True)
        self.QS_date.setDate(QtCore.QDate(2019, 10, 1))
        self.QS_date.setObjectName("QS_date")
        self.horizontalLayout.addWidget(self.QS_date)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.JS_date = QtWidgets.QDateEdit(self.centralwidget)
        self.JS_date.setMinimumSize(QtCore.QSize(0, 30))
        self.JS_date.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.JS_date.setFont(font)
        self.JS_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 12, 14), QtCore.QTime(0, 0, 0)))
        self.JS_date.setCalendarPopup(True)
        self.JS_date.setObjectName("JS_date")
        self.horizontalLayout.addWidget(self.JS_date)
        self.ST_cx_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ST_cx_button.setFont(font)
        self.ST_cx_button.setObjectName("ST_cx_button")
        self.horizontalLayout.addWidget(self.ST_cx_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.XS_table_w = QtWidgets.QTableWidget(self.centralwidget)
        self.XS_table_w.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.XS_table_w.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.XS_table_w.setObjectName("XS_table_w")
        self.XS_table_w.setColumnCount(7)
        self.XS_table_w.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.XS_table_w.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.XS_table_w.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.XS_table_w.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.XS_table_w.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.XS_table_w.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.XS_table_w.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.XS_table_w.setHorizontalHeaderItem(6, item)
        self.XS_table_w.horizontalHeader().setCascadingSectionResizes(False)
        self.XS_table_w.horizontalHeader().setDefaultSectionSize(190)
        self.XS_table_w.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout.addWidget(self.XS_table_w, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.XS_d_line = QtWidgets.QLineEdit(self.centralwidget)
        self.XS_d_line.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.XS_d_line.setFont(font)
        self.XS_d_line.setReadOnly(True)
        self.XS_d_line.setObjectName("XS_d_line")
        self.horizontalLayout_3.addWidget(self.XS_d_line)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.XS_people_line = QtWidgets.QLineEdit(self.centralwidget)
        self.XS_people_line.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.XS_people_line.setFont(font)
        self.XS_people_line.setReadOnly(True)
        self.XS_people_line.setObjectName("XS_people_line")
        self.horizontalLayout_3.addWidget(self.XS_people_line)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.XS_SL_line = QtWidgets.QLineEdit(self.centralwidget)
        self.XS_SL_line.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.XS_SL_line.setFont(font)
        self.XS_SL_line.setReadOnly(True)
        self.XS_SL_line.setObjectName("XS_SL_line")
        self.horizontalLayout_3.addWidget(self.XS_SL_line)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.XS_JE_line = QtWidgets.QLineEdit(self.centralwidget)
        self.XS_JE_line.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.XS_JE_line.setFont(font)
        self.XS_JE_line.setReadOnly(True)
        self.XS_JE_line.setObjectName("XS_JE_line")
        self.horizontalLayout_3.addWidget(self.XS_JE_line)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "统计"))
        self.label.setText(_translate("MainWindow", "起始日期："))
        self.QS_date.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_2.setText(_translate("MainWindow", "结束日期："))
        self.JS_date.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.ST_cx_button.setText(_translate("MainWindow", "查询"))
        item = self.XS_table_w.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "流水号"))
        item = self.XS_table_w.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "条码"))
        item = self.XS_table_w.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "名称"))
        item = self.XS_table_w.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "规格"))
        item = self.XS_table_w.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "类别"))
        item = self.XS_table_w.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "数量"))
        item = self.XS_table_w.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "金额"))
        self.label_6.setText(_translate("MainWindow", "总计："))
        self.label_4.setText(_translate("MainWindow", "销售门店"))
        self.label_3.setText(_translate("MainWindow", "销售员"))
        self.label_7.setText(_translate("MainWindow", "数量"))
        self.label_8.setText(_translate("MainWindow", "金额"))
